'use client';

import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  Award,
  Smile,
  Meh,
  Frown,
  Target,
  CheckCircle,
  XCircle,
  TrendingUp,
  Clock,
  Sparkles,
  Loader2,
} from 'lucide-react';
import { cn } from '@/lib/utils';


export function CallScorecard({ callId, scorecard, onGenerate, generating }) {
  if (!scorecard && !onGenerate) {
    return null;
  }

  if (!scorecard) {
    return (
      <Card className="p-8">
        <div className="text-center">
          <Sparkles className="w-12 h-12 text-purple-600 mx-auto mb-4" />
          <h3 className="text-lg font-semibold mb-2">Generate AI Scorecard</h3>
          <p className="text-muted-foreground mb-6">
            Get insights about this call using AI analysis
          </p>
          <Button
            onClick={onGenerate}
            disabled={generating}
            className="gap-2"
          >
            {generating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                Generate Scorecard
              </>
            )}
          </Button>
        </div>
      </Card>
    );
  }

  const getSentimentIcon = (sentiment) => {
    switch (sentiment.toLowerCase()) {
      case 'positive':
        return <Smile className="w-6 h-6 text-green-600" />;
      case 'negative':
        return <Frown className="w-6 h-6 text-red-600" />;
      default:
        return <Meh className="w-6 h-6 text-yellow-600" />;
    }
  };

  const getSentimentColor = (sentiment) => {
    switch (sentiment.toLowerCase()) {
      case 'positive':
        return 'bg-green-100 text-green-700 border-green-200';
      case 'negative':
        return 'bg-red-100 text-red-700 border-red-200';
      default:
        return 'bg-yellow-100 text-yellow-700 border-yellow-200';
    }
  };

  const getQualityColor = (score) => {
    if (score >= 8) return 'text-green-600';
    if (score >= 6) return 'text-yellow-600';
    return 'text-red-600';
  };

  return (
    <Card className="p-6">
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-lg font-semibold flex items-center gap-2">
          <Award className="w-5 h-5 text-purple-600" />
          AI Call Scorecard
        </h3>
        <span className="text-xs text-muted-foreground">
          Generated by AI
        </span>
      </div>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {/* Quality Score */}
        <div className="text-center p-6 bg-gradient-to-br from-purple-50 to-blue-50 rounded-lg border border-purple-100">
          <Award className="w-8 h-8 text-purple-600 mx-auto mb-3" />
          <p className="text-sm text-muted-foreground mb-2">Quality Score</p>
          <p className={cn('text-4xl font-bold', getQualityColor(scorecard.quality_score))}>
            {scorecard.quality_score}/10
          </p>
        </div>

        {/* Sentiment */}
        <div className="text-center p-6 bg-gradient-to-br from-gray-50 to-gray-100 rounded-lg border">
          <div className="mx-auto mb-3">
            {getSentimentIcon(scorecard.sentiment)}
          </div>
          <p className="text-sm text-muted-foreground mb-2">Sentiment</p>
          <span className={cn(
            'inline-flex items-center px-3 py-1 rounded-full text-sm font-medium border',
            getSentimentColor(scorecard.sentiment)
          )}>
            {scorecard.sentiment.charAt(0).toUpperCase() + scorecard.sentiment.slice(1)}
          </span>
        </div>

        {/* Goal Completion */}
        {scorecard.goal_completed !== null && (
          <div className="text-center p-6 bg-gradient-to-br from-green-50 to-emerald-50 rounded-lg border border-green-100">
            {scorecard.goal_completed ? (
              <CheckCircle className="w-8 h-8 text-green-600 mx-auto mb-3" />
            ) : (
              <XCircle className="w-8 h-8 text-red-600 mx-auto mb-3" />
            )}
            <p className="text-sm text-muted-foreground mb-2">Goal Status</p>
            <p className={cn(
              'text-lg font-bold',
              scorecard.goal_completed ? 'text-green-600' : 'text-red-600'
            )}>
              {scorecard.goal_completed ? 'Completed' : 'Not Completed'}
            </p>
          </div>
        )}

        {/* Accuracy Score */}
        {scorecard.accuracy_score !== null && (
          <div className="text-center p-6 bg-gradient-to-br from-blue-50 to-cyan-50 rounded-lg border border-blue-100">
            <Target className="w-8 h-8 text-blue-600 mx-auto mb-3" />
            <p className="text-sm text-muted-foreground mb-2">Accuracy</p>
            <p className="text-3xl font-bold text-blue-600">
              {Math.round(scorecard.accuracy_score * 100)}%
            </p>
          </div>
        )}

        {/* Response Time */}
        {scorecard.response_time_avg !== null && (
          <div className="text-center p-6 bg-gradient-to-br from-orange-50 to-amber-50 rounded-lg border border-orange-100">
            <Clock className="w-8 h-8 text-orange-600 mx-auto mb-3" />
            <p className="text-sm text-muted-foreground mb-2">Avg Response Time</p>
            <p className="text-2xl font-bold text-orange-600">
              {(scorecard.response_time_avg / 1000).toFixed(1)}s
            </p>
          </div>
        )}
      </div>

      {/* Key Topics */}
      {scorecard.key_topics && scorecard.key_topics.length > 0 && (
        <div className="mt-6">
          <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
            <TrendingUp className="w-4 h-4" />
            Key Topics Discussed
          </h4>
          <div className="flex flex-wrap gap-2">
            {scorecard.key_topics.map((topic, index) => (
              <span
                key={index}
                className="inline-flex items-center px-3 py-1 rounded-full text-sm bg-purple-100 text-purple-700 border border-purple-200"
              >
                {topic}
              </span>
            ))}
          </div>
        </div>
      )}
    </Card>
  );
}